name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: abdullah8a0
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: USA/boston
          repositories: 200
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: true
          commits_authoring: abdullah8a0@gmail.com, abd880@mit.edu
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github, renderscript:#dea584
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 180
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
